### ISSUE TITLE
Binding Address.country an ISO-Ländercodes

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-stu3#1]
ValueSet "jurisdiction" ist suboptimal.
https://chat.fhir.org/#narrow/stream/terminology/topic/ISO.20country.20code.20ValueSet

**Comment by simoneOnFhir** [comment]
http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13330

**Comment by lhitc** [comment]
Nach Klärung muss auch  	Example-organization-de-betriebsstaette-1.xml angepasst werden.

**Comment by lhitc** [comment]
Kann man überhaupt formal ein ValueSet an ein Element vom Typ string binden?
Das betrifft analog #6

**Comment by lhitc** [comment]
https://chat.fhir.org/#narrow/stream/conformance/topic/ValueSet.20binding.20for.20string.20elements.3F

**Comment by lhitc** [comment]
und geklärt, ValueSet-Binding an string ist zulässig.

**Comment by simoneOnFhir** [comment]
Das Anlage-8-CodeSystem int jetzt vorhanden!

**Comment by lhitc** [comment]
TC FHIR: nicht mehr für Ballot 09/2017, da noch keine Antwort zum GF-Tracker-Item seitens HL7 Vocab vorliegt.

**Comment by tliebscher** [comment]
Die Entscheidung über Binding ist mir noch nicht klar. Die Kommentarsektion suggeriert noch, dass auch ohne Binding einfach der Freitextname verwendet werden kann. Ich verstehe das so, dass das konkrete Binding (alpha2, alpha3) den ableitenden Profilen offen gelassen werden soll, aber wir grundsätzlich ein Binding wollen. Oder habe ich bewusst die Wahl zwischen Freitext, alpha2, alpha3, etwas anderes?

https://simplifier.net/BasisprofilDE/address-de-basis-0.2/~details
Address.country
--
Definition | Staat (vorzugsweise als 2-Stelliger ISO-Ländercode). Es obliegt abgeleiteten Profilen, hier die Verwendung der ISO-Ländercodes verbindlich vorzuschreiben
Cardinality | 0..1
**Binding** | The codes SHOULD be taken from http://hl7.org/fhir/ValueSet/jurisdiction
Type | string
Comments | ISO 3166 3 letter codes can be used **in place of a full country name**.

**Comment by simoneOnFhir** [comment]
ValueSet 2-letter-country-code wurde von Vocab definiert und in R4 publiziert. In R4 Addres-Profil entsprechend angpasst.
