### ISSUE TITLE
KBV-Codesysteme nach Möglichkeit durch KBV verwalten lassen

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-stu3#105]
Da die KBV inzwischen selbst FHIR-basierte Spezifikationen herausgibt, erscheint es sinnvoll, wenn die KBV-Schlüsseltabellen auch in Form von FHIR-CodeSystem und -ValueSet-Ressourcen  direkt von der KBV herausgegeben werden. Dies insbesondere auch vor dem Hintergrund der quartalsmäßigen Wartung der Schlüsseltabellen durch die KBV.

Hierzu bedarf es einer entsprechenden Entscheidung der KBV (bereits angeregt).
Sofern/sobald dies realisiert wird, können die entsprechenden Terminologie-Ressourcen aus den Basisprofilen entfernt und die Bindings in den Profilen und Extensions entsprechend überarbeitet werden.

**Comment by wroos** [comment]
Alle KBV-Schlüsseltabellen (http://applications.kbv.de/keytabs/ita/schluesseltabellen.asp) liegen als FHIR-Ressourcen vor. Derzeit nur als zip-File unter ftp://ftp.kbv.de/ita-update/Stammdateien/Schluesseltabellen/. Perspektivisch sollen diese aber auch über die Schlüsseltabellen-Seite angeboten werden. So sind die Ressourcen dann immer auf dem aktuellen Stand.

**Comment by simoneOnFhir** [comment]
Aufgabe wird in R4 issues weitergeführt, wird in STU3 nicht mehr geändert...
