### ISSUE TITLE
Rechtschreibung

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de-stu3#114]
https://simplifier.net/BasisprofilDE/address-de-basis-0.2/~details
Definition:
...
Insbesondere bei ausländischen **Adressen** oder Adressen, die nicht durch Einlesen einer elektronischen Versichertenkarte erfasst wurden, sind abweichende Strukturen möglich. Die Verwendung der Extensions ist nicht verpflichtend.

**Comment by simoneOnFhir** [comment]
Text kommt in R4 nicht mehr vor.
