### ISSUE TITLE
Patient.managingOrganization Zweck nicht klar

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de-stu3#116]
Worum geht es hier? Um den primären (Haupt-)Behandler (z.B. meinen Hausarzt) oder um den Custodian/Record Keeper dieser Akte, im Sinne von z.B. Haftung für den Inhalt?
 
https://simplifier.net/BasisprofilDE/patient-de-basis-0.2/~details
Patient.managingOrganization
--
Definition | **haupt-behandelnde Organisation** nach deutschem Profil. Dieses Profil enthält für Deutschland spezififische Besonderheiten und Extensions.
Cardinality | 0..1
Type | Reference(Organisation, deutsches Basisprofil (Version 0.2))
Requirements | Need to know who recognizes this patient record, manages and updates it.
Comments | There is **only one managing organization for a specific patient record. Other organizations will have their own Patient record**, and may use the Link property to join the records together (or a Person resource which can include confidence ratings for the association).

**Comment by simoneOnFhir** [comment]
Duplikat von #142
