### ISSUE TITLE
Organization.identifier.period.start/end Beschreibung allgemeiner fassen

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de-stu3#117]
Nicht jeder Identifier enthält eine BSNR. Beschreibung kann hier allgemeingültig gehalten werden.

https://simplifier.net/BasisprofilDE/organization-de-basis-0.2/~details
Organization.identifier.period.start
--
Definition | Beginn der **~~BSNR~~** Gültigkeit
Cardinality | 0..1 see per-1 for conditions
Type | dateTime
Comments | If the low element is missing, the meaning is that the low boundary is not known.
Organization.identifier.period.end
Definition | Ende der **~~BSNR~~** Gültigkeit. leer, falls aktuell gültig.
Cardinality | 0..1 see per-1 for conditions
Type | dateTime
Comments | The high value includes any matching date/time. i.e. 2012-02-03T10:00:00 is in a period that has a end value of 2012-02-03.
Meaning if Missing | If the end of the period is missing, it means that the period is ongoing

**Comment by simoneOnFhir** [comment]
Der Text wird nur in dem Slice verwendet, bei dem es konkret um die BSNR geht...
