### ISSUE TITLE
Allergien ExposureRoute Coding System Vorgaben

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de-stu3#119]
Müssen wir hier in Zukunft EDQM unterstützen?

https://simplifier.net/basisprofilde/allergyintolerance-de-basis-0.2

AllergyIntolerance.reaction.exposureRoute
--
Definition | Identification of the route by which the subject was exposed to the substance.
Cardinality | 0..1
Binding | A coded concept describing the route or physiological path of administration of a therapeutic agent into or onto the body of a subject.For example codes, see http://hl7.org/fhir/ValueSet/route-codes
Type | CodeableConcept
Comments | Coding of the route of exposure with a terminology should be used wherever possible.

**Comment by simoneOnFhir** [comment]
Nein, es handelt sich um ein Binding vom Typ "example".
Es ist also kein MUSS, nicht einmal eine Präferenz seitens HL7
