### ISSUE TITLE
Abgeleitetes Coverage Profil bei subscriber und beneficiary auch mit Standard Patient?

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de-stu3#123]
https://simplifier.net/BasisprofilDE/coverage-de-basis-0.2/~details

Sollte nicht auch Patient möglich sein?
Coverage.subscriber
--
Definition | Hauptversicherte Person (ggf. abweichend von beneficiary), z.B. bei Familienversicherung
Cardinality | 0..1
Type | **Choice of: Reference(RelatedPerson) \|  Reference(Patient) \| Reference(Patient, deutsches Basisprofil (Version 0.2))**
....
Coverage.beneficiary
Definition | Person, auf die sich die Kostenübernahme bezieht (der Patient)
Cardinality | 1..1
Type | **Choice of: Reference(Patient) \| Reference(Patient, deutsches Basisprofil (Version 0.2))**

**Comment by simoneOnFhir** [comment]
In R4 erledigt
