### ISSUE TITLE
FHIR-Repräsentation der KBV-Schlüsseltabellen verwenden

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-stu3#124]
Die KBV-Schlüsseltabellen sind jetzt als FHIR-CodeSystem-Ressourcen veröffentlicht:

ftp://ftp.kbv.de/ita-update/Stammdateien/Schluesseltabellen/KBV_Schluesseltabellen_FHIR.zip

Demzufolge können die bisher übergangsweise in den deutschen Basisprofilen verwendeten CodeSystem-Ressourcen aus dem KBV-Bereich entfallen. Entsprechende Referenzen auf die Codesysteme müssen auf die Namen lt. KBV-Vorgabe angepasst werden.

**Comment by simoneOnFhir** [comment]
In R4 erledigt
