### ISSUE TITLE
zur Diskussion: Vereinfachung der Basis-Profile

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-stu3#125]
Das Slicing für verschiedene Optionale Identifier führt aktuell zu recht unleserlichen Darstellungen in abgeleiteten Profilen. Da wir den Discriminator nicht erzwingen können, bringt das für die Validierung keinen Vorteil. Ich würde Vorschlagen, statt dessen für verschiedene Identifier oder Codings eigene Identifier- bzw. Coding-Profile zu erstellen, diese aber nicht in den Ressourcen-Profilen zu verlinken. (lediglich im Prosa-Text im IG) 
Ein weiterer Vorteil wäre die besserer Wiederverwendbarkeit.
Gleiches gilt für die Extensions: evtl. besser nur die Extensions und deren Einsatz zu definieren als diese  optional in die Profile einzubauen...
Beispiel: Profile Addresse-erweitert mit Extensions definieren, aber nicht in Patient einbauen...

Möglicherweise hätte das zur Folge, dass die Basis-Profile weniger (gar keine!?) Ressourcen-Profile, dafür aber mehr modulare Datentyp-Profile, Extensions, NamingSystems enthalten, die dann in Use-Case-Profilen verwendet werden können...

**Comment by lhitc** [comment]
Weniger Profile sind wahrscheinlich sinnvoll. Man sollte dann nur im IG-Text klar und ausführlich beschreiben, wie das ganze anzuwenden ist.
Gerade für Neueinsteiger ist das relativ simple "Ableiten vom Basisprofil X" doch einfacher als das vorgeschlagene Konzept.

Auf "0 Ressourcen-Profile" werden wir wahrscheinlich nicht ganz kommen, weil manches doch nur im Rahmen von Ressourcen-Profilen darstellbar ist, z.B. ICD-10-GM (zumindest in seiner jetzigen Form) oder Observations mit Komponenten.

Gerade bei Observations droht natürlich eine Inflation an Profilen. Da sollten wir m.E. schauen, dass es ab R4 mit ObservationDefinition voran geht, speziell vor dem Hintergrund Validierungs-Support.

**Comment by simoneOnFhir** [comment]
In R4 umgesetzt
