### ISSUE TITLE
regulären Ausdruck(regex) des Datentyps date für das eGK-Geburtstdatum

### ISSUE THREAD

**Issue by wroos** [hl7germany/basisprofil-de-stu3#127]
Gemäß der eGK-Spezifikation sind folgende Konstellationen des Geburtsdatums möglich:
- nur der Tag ist 00
- Tag und Monat sind jeweils 00 --> 00.00
- Tag, Monat und Jahr sind 00 --> 00.00.0000

Der reguläre Ausdruck des date-Datentyps (-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1]))?)?) erlaubt den Tag 00, allerdings nicht den Monat 00. In bestimmten Fällen ist es notwendig das Geburtsdatum 00.00.0000 zu übertragen. Daher wäre es von großem Vorteil dieses zu ermöglichen.

**Comment by simoneOnFhir** [comment]
Diskussion: https://chat.fhir.org/#narrow/stream/179183-german-(d-a-ch)/topic/.5Bbasis.5D.20Issue.23127.3A.20RegEx.20f.C3.BCr.20Geburtsdatum

**Comment by simoneOnFhir** [comment]
Resolution:

> Die Kardinalität von birthDate im VSDM-Profil wird auf 0..1 gesetzt. Im Beschreibungstext (Basis und VSDM) von birthDate wird der Hinweis auf das Mapping der VSDM-Nullwerte auf partielle Daten ergänzt.

Disposition: Modifiziert angenommen
Motion: Simone Heckmann 
Second: Stefan Lang 
Dafür: 3
Dagegen: 0

**Comment by simoneOnFhir** [comment]
In R4 IG erläutert: https://simplifier.net/guide/basisprofil-de-r4/Geburtsdatum
