### ISSUE TITLE
Jurisdiction-ValueSet darf nicht an country gebunden sein

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-stu3#173]
Im address-de-basis-Profil ist das ValueSet http://hl7.org/fhir/ValueSet/jurisdiction an country gebunden.

country ist vom Datentyp string, kann also nur den Code enthalten, nicht den Codesystem-Namen.

Das o.g. ValueSet setzt sich aber aus mehreren Codesystemen zusammen, bei denen die Codes teilweise identisch sind.
Besonders relevantes Beispiel: in der Instanz ist nicht unterscheidbar, ob die Angabe "DE" für "Deutschland" oder "Delaware" steht.

Das preferred binding sollte daher entfernt werden und zu einem späteren Zeitpunkt, wenn ein echtes Staaten-ValueSet seitens HL7 International benannt ist, durch ein Binding an dieses ersetzt werden.

**Comment by simoneOnFhir** [comment]
In R4 ersetzt durch ein preferred binding an http://hl7.org/fhir/ValueSet/iso3166-1-2
