### ISSUE TITLE
Lizenzbedingungen ISO 3166 beachten

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-stu3#176]
address-de-basis bindet in country das Juristiction ValueSet, das ISO 3166 enthält.
ISO 3166 ist formal lizenzpflichtig (was u.a. auch ein Grund dafür ist, dass es nicht in FHIR existiert).
Wie soll hiermit in Zukunft umgegangen werden?

**Comment by simoneOnFhir** [comment]
Anfrage an TC Terminologien: https://chat.fhir.org/#narrow/stream/179316-german.2Fterminologien

**Comment by lhitc** [comment]
Diskussion wird derzeit international geführt:

https://chat.fhir.org/#narrow/stream/207835-IPS/topic/urn.3Aiso.3Astd.3Aiso.3A3166.20license

**Comment by patrick-werner** [comment]
> Update from the German DIMDI/HL7 enquiry to ISO:
> Patricia Cook from ISO Central Secretariat (responsible for 3166): "You don’t need any permission to include the ISO 3166 country codes in lists or software, this is fine" :)
