### ISSUE TITLE
pattern entfernen

### ISSUE THREAD

**Issue by patrick-werner** [hl7germany/basisprofil-de-stu3#177]
https://github.com/hl7germany/basisprofil-de-stu3/search?q=patternCode&unscoped_q=patternCode
enthalten alle pattern welche entfernt werden müssen.

**Comment by lhitc** [comment]
HAPI-FHIR 4.1.0 macht mit den aktuell verwendeten Patterns ("matches('[01]')" u.ä. weiterhin Probleme.

**Comment by simoneOnFhir** [comment]
Ist das nicht ein HAPI-Bug?!

**Comment by patrick-werner** [comment]
all fixed now. War ein Bug im Java Validator und übersehene pattern.
