### ISSUE TITLE
Examples in die Profile integrieren

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-stu3#35]
Die Beispiele sollten (via Element.example) in die jeweiligen Profile integriert sein.
Auf Toplevel-Ebene wird dies aber in Simplifier derzeit nicht abgebildet.

Daher nicht mehr im Ballot 09/2017 realisierbar. Simplifier-Issue ist bereits erstellt.

**Comment by lhitc** [comment]
Bitte keine Änderungen hier bis nach Release 0.2

**Comment by simoneOnFhir** [comment]
Beispiele können als Markdown in den IG eingefügt werden. Macht mehr Sinn, um die Profile nicht mit überflüssigem Content zu überlasten und es ist einfacher, die Beispiel zu kommentieren, wenn man Sie direkt im IG einfügt...
