### ISSUE TITLE
Organisation-Profil für KBV-Kostenträger (DMP)

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-stu3#65]
Attribute gemäß VSDM:
- [x] WOP-Kennzeichen/KV-Bereich (Extension-Code) 0..1
- [ ] VK-Nummer (Identifier/NamingSystem) 0..1 
       Invariante: nur bei gesetzlichen KT
- [x] SKT-Zusatzangabe (String) 0..1 
       Invariante: nur bei sonstigen KT

**Comment by simoneOnFhir** [comment]
coverage-de-gkv aktualisiert mit extensions gemäß VSDM
- [ ] Einlesedatum der Karte fehlt noch und 
- [ ] NamingSystem für anonym. kvid.
- [ ] Beschreibungstexte der Extension-Elemente fehlen noch
- [ ] ValueSet-Bindung und Kardinalitäten prüfen

**Comment by patrick-werner** [comment]
- Beschreibungstexte der Extensions in <title> gepackt, sollte aber lieber in description (TC Vote pending)
- ValueSet Binding von WOP auf KBV-KV hinzugefügt https://github.com/hl7germany/basisprofil-de/commit/0debcf06f1176c6fe233d237e779ae193dfb0f4b
- WOP Kennzeichen als Feature-Branch erstellt: https://github.com/hl7germany/basisprofil-de/commit/26dc90485af372b9ac2245b75dd324250309880e

**Comment by lhitc** [comment]
Die SKT-Zusatzangabe ist lt. KBV eine Eigenschaft des Versicherungsverhältnisses.
Sie kann auch Patienten oder(!) den Kostenträger identifizieren.
Vgl. S. 18 in ftp://ftp.kbv.de/ita-update/Stammdateien/SDKV/KBV_ITA_VGEX_Datensatzbeschreibung_SDKV.pdf

=> Gehört also zu Coverage, keinesfalls zum Kostenträger.

**Comment by lhitc** [comment]
SKT-Zusatzangabe als Extension für Coverage definiert.
Ist aber derzeit in keinem Coverage-Profil eingebunden.

**Comment by simoneOnFhir** [comment]
Gehört in die Hoheit der KBV...
