### ISSUE TITLE
Inkonsistente Bezeichnungen in Profil-Referenzen vereinheitlichen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-stu3#67]
![image](https://user-images.githubusercontent.com/28486740/31965642-40ced3ae-b908-11e7-8a00-fe8ce7ac8638.png)

**Comment by patrick-werner** [comment]
Die Bezeichnung welche hier gerendert wird ist StructureDefinition.name
Leider sind nicht alle erlaubten Referencen direkt von Simplifiert in der Overview ersichtlich, da einfach mittels ... abgeschnitten wird.

![simplifier_net_-_basisprofil_de__draft____coverage-de-basis](https://user-images.githubusercontent.com/7199495/31989873-d2be11a6-b973-11e7-94b5-0f5ec8e5b1e6.jpg)

Feedback an Simplifier wurde abgegeben.

- [ ] Antwort von Furore erhalten

**Comment by lhitc** [comment]
Bitte keine Änderungen hier bis nach Release 0.2

**Comment by lhitc** [comment]
Bitte keine Änderungen hier bis nach Release 0.2

**Comment by simoneOnFhir** [comment]
In R4 hinfällig, da es keine Basis-Profile für Patient/Organization mehr gibt...
