### ISSUE TITLE
VSDM Pfadangaben und KV-Feldkennungen ins Mapping einfügen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de-stu3#70]
Siehe Anhang:
[Mapping VSDM--KVDT.pdf](https://github.com/hl7germany/basisprofil-de/files/1449147/Mapping.VSDM--KVDT.pdf)

- [x] KV-Feldkennungen in Coverage hinterlegen
- [ ] VSDM-Pfade in Coverage hinterlegen
- [x] KV-Feldkennungen in Patient hinterlegen
- [ ] VSDM-Pfade in Patient hinterlegen

**Comment by simoneOnFhir** [comment]
Bei Furore angefragt, da Mappings auf Simplifier noch nicht gerendert werden...

**Comment by patrick-werner** [comment]
ich übernehme die VSDM Pfade Todos

**Comment by simoneOnFhir** [comment]
Mappings gefixed, allerding werden die Mappings aus humanname-de-basis in Patient-de-basis nicht angezeigt, von address-de-basis hingegen schon. Gemeldet an Furore

**Comment by simoneOnFhir** [comment]
Obsolet, da es jetzt die Mapping Language gibt, also wenn schon Mapping, dann richtig....
