### ISSUE TITLE
CodeSystems und ValueSets unter hl7.org erhalten neue canonical URLs

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de-stu3#96]
Muss beim Switch auf FHIR R4 in den deutschen ValueSets und ggf. Profilen (ValueSet bindings) nachgezogen werden.

Betrifft derzeit die Terminologie-Ressourcen zu v2 und v3, wahrscheinlich auch diejenigen zu FHIR.

Vgl. https://chat.fhir.org/#narrow/stream/125-fhir.2Finfrastructure-wg/subject/Terminology

**Comment by lhitc** [comment]
Offizielles Announcement: https://chat.fhir.org/#narrow/stream/4-implementers/subject/Change.20to.20value.20set.20and.20code.20system.20URLS

**Comment by simoneOnFhir** [comment]
erl. durch Umstellung auf R4 StructureDefs...
